### ISSUE TITLE
Laravel构建个人博客 | I'm 晚黎

### ISSUE THREAD

**Issue by lanceWan** [lanceWan/BLog#2]
http://www.iwanli.me/iwanli/2018/11/11/laravel-my-blog-01.html

**Comment by lanceWan** [comment]
晚黎留言

**Comment by chenYvv** [comment]
沙发！

**Comment by yuzhe10** [comment]
Hi晚黎, 你自己的这个博客源码会放出来吗，很喜欢这个前端效果

**Comment by lanceWan** [comment]
@yuzhe10   会的

**Comment by yuzhe10** [comment]
能发发一份呢？@lanceWan

**Comment by lanceWan** [comment]
@yuzhe10 https://www.creative-tim.com/  我是在这个网站下的  有免费的，还有其他版本的都挺好看的，一次性都告诉你把~~

**Comment by mofashi998** [comment]
晚黎你已经很久没有更新内容了，我们已经饥渴难耐了！

**Comment by yuzhe10** [comment]
@lanceWan thx!

**Comment by liaoshanjin** [comment]
哇，我也想要一个这样的博客，很简洁，很漂亮
